########################################################################################################################
# GLOBAL
########################################################################################################################

global:

  cluster:

    istio:
      enabled: false

    storage:
      data:
        spec: {}
#          storageClassName:

  image:
    registry: ${docker.registry}
    repository: ${docker.image}
    tag: ${docker.tag}
    pullPolicy: Always
    pullSecrets: []

########################################################################################################################
# LOCAL
########################################################################################################################

nameOverride: edusharing-elasticsearch

########################################################################################################################

replicaCount: 3

########################################################################################################################

service:

  port:
    api: 9200
    gossip: 9300

########################################################################################################################

config:

  jvm:
    ram:
      minPercentage: "50"
      maxPercentage: "50"

  store:
    mmap: false

########################################################################################################################

nodeAffinity: {}
podAntiAffinity: "soft"

tolerations: []

########################################################################################################################

persistence:

  data:
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi

########################################################################################################################

podSecurityContext:

  runAsUser: 1000
  fsGroup: 1000

securityContext:

  capabilities:
    drop:
    - ALL

########################################################################################################################

terminationGracePeriod: 120

livenessProbe:

  failureThreshold: 3
  initialDelaySeconds: 1200
  periodSeconds: 10
  timeoutSeconds: 5

readinessProbe:

  failureThreshold: 1
  initialDelaySeconds: 30
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5

########################################################################################################################

resources:

  limits:
    cpu: 200m
    memory: 2Gi
  requests:
    cpu: 200m
    memory: 2Gi

########################################################################################################################

metrics:

  enabled: true

  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 100m
      memory: 100Mi

  securityContext: {}

########################################################################################################################
