apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "edusharing_mariadb.name" . }}-file
  labels: {{ include "edusharing_mariadb.labels" . | nindent 4 }}
data:
  my_custom.cnf: |
    {{- range $key1, $value1 := .Values.config.extra }}
    [{{ $key1 }}]
    {{- range $key2, $value2 := $value1 }}
    {{ $key2 }}{{ if $value2 }}={{ $value2 }}{{ end }}
    {{- end }}
    {{- end }}
    [mysqld]
    bind_address={{ if .Values.global.cluster.istio.enabled }}127.0.0.1{{ else }}0.0.0.0{{ end }}
