apiVersion: v1
kind: Secret
metadata:
  name: {{ include "edusharing_mariadb.fullname" . }}-env
  labels: {{ include "edusharing_mariadb.labels" . | nindent 4 }}
type: Opaque
data:
  MARIADB_ROOT_PASSWORD: {{ .Values.config.password | b64enc | quote }}
  MARIADB_PASSWORD: {{ .Values.config.password | b64enc | quote }}
  MARIADB_USER: {{ .Values.config.username | b64enc | quote }}
