apiVersion: v2

name: ${helm.prefix}-repository-search-solr
description: ${helm.prefix}-repository-search-solr

icon: ${helm.chart.icon}

version: ${helm.chart.version}
appVersion: ${docker.tag}
kubeVersion: "${helm.kube.version}"
