########################################################################################################################
# GLOBAL
########################################################################################################################

global:

  image:
    registry: ${docker.registry}
    pullPolicy: Always
    pullSecrets: []

  istio:
    enabled: false

########################################################################################################################
# LOCAL
########################################################################################################################

nameOverride: edusharing-elasticsearch
fullnameOverride: ""

########################################################################################################################

image:

  repository: ${docker.image}-elasticsearch
  tag: ${docker.tag}

########################################################################################################################

replicaCount: 3

########################################################################################################################

service:

  port:
    api: 9200
    gossip: 9300

########################################################################################################################

config:

  jvm:
    ram:
      minPercentage: "50"
      maxPercentage: "50"

########################################################################################################################

nodeAffinity: {}
podAntiAffinity: "" # "soft" or "hard"

tolerations: []

########################################################################################################################

persistence:

  data:
    spec:
      accessModes: [ "ReadWriteOnce" ]
#     storageClassName:
      resources:
        requests:
          storage: 5Gi

########################################################################################################################

podSecurityContext:

  runAsUser: 1000
  fsGroup: 1000

securityContext:

  capabilities:
    drop:
      - ALL

########################################################################################################################

terminationGracePeriod: 120

livenessProbe:

  failureThreshold: 3
  initialDelaySeconds: 300
  periodSeconds: 10
  timeoutSeconds: 5

readinessProbe:

  failureThreshold: 1
  initialDelaySeconds: 30
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5

########################################################################################################################

resources:

  limits:
    cpu: 200m
    memory: 2Gi
  requests:
    cpu: 200m
    memory: 2Gi

########################################################################################################################
