repos:
  - repo: https://github.com/bitnami/readme-generator-for-helm
    rev: "2.6.1"
    hooks:
    - id: helm-readme-generator
      pass_filenames: false
      always_run: true
      args: [--readme=archetypes/project/src/main/resources/archetype-resources/deploy/docker/helm/src/main/chart/README.md, --values=archetypes/project/src/main/resources/archetype-resources/deploy/docker/helm/src/main/chart/values.yaml]
    - id: helm-readme-generator
      pass_filenames: false
      always_run: true
      args: [--readme=archetypes/project/src/main/resources/archetype-resources/repository/deploy/docker/helm/src/main/chart/README.md, --values=archetypes/project/src/main/resources/archetype-resources/repository/deploy/docker/helm/src/main/chart/values.yaml]
