apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "edusharing_rediscluster.name" . }}-env
  labels: {{ include "edusharing_rediscluster.labels" . | nindent 4 }}
data:
  ALLOW_EMPTY_PASSWORD: "yes"
  REDIS_NODES: '{{ range $i := until (include "edusharing_rediscluster.replicas" . | int) }}{{ include "edusharing_rediscluster.name" $ }}-{{ $i }}.{{ include "edusharing_rediscluster.name" $ }}-headless {{ end }}'
