apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "edusharing_rediscluster.fullname" . }}-init
  labels: {{ include "edusharing_rediscluster.labels" . | nindent 4 }}
    app.kubernetes.io/component: init
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-delete-policy: hook-succeeded
    {{- if .Values.global.istio.enabled }}
    sidecar.istio.io/inject: "true"
    {{- end }}
spec:
  completions: 1
  parallelism: 1
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: {{ include "edusharing_rediscluster.name" . }}
        image: {{ .Values.global.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        command:
          - "/bin/bash"
          - "-ec"
          - |
            [[ -f /opt/bitnami/redis/etc/redis.conf ]] || {
              cp /opt/bitnami/redis/etc/redis-default.conf /opt/bitnami/redis/etc/redis.conf
            }
            /opt/bitnami/scripts/redis-cluster/entrypoint.sh /opt/bitnami/scripts/redis-cluster/run.sh
        env:
        - name: REDIS_CLUSTER_CREATOR
          value: "yes"
        - name: REDIS_CLUSTER_CREATOR_WAIT_TIME_AFTER_NODE_READY
          value: {{ .Values.config.cluster.wait | quote }}
        - name: REDIS_CLUSTER_REPLICAS
          value: {{ .Values.config.cluster.replicas | quote }}
        envFrom:
        - configMapRef:
            name: {{ include "edusharing_rediscluster.fullname" . }}-env
        volumeMounts:
          - name: conf
            mountPath: /opt/bitnami/redis/etc/redis-default.conf
            subPath: redis-default.conf
        {{- with .Values.resources }}
        resources: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.securityContext }}
        securityContext: {{ toYaml . | nindent 10 }}
        {{- end }}
      {{- with .Values.global.image.pullSecrets }}
      imagePullSecrets: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{ with .Values.terminationGracePeriod }}
      terminationGracePeriodSeconds: {{ . }}
      {{- end }}
      {{- with .Values.nodeAffinity }}
      affinity:
        nodeAffinity: {{ toYaml . | nindent 10 }}
      {{- end }}
      volumes:
        - name: conf
          configMap:
            name: {{ include "edusharing_rediscluster.fullname" . }}-conf
