apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "edusharing_rediscluster.name" . }}
  labels: {{ include "edusharing_rediscluster.labels" . | nindent 4 }}
spec:
  podManagementPolicy: Parallel
  replicas: {{ include "edusharing_rediscluster.replicas" . }}
  selector:
    matchLabels: {{ include "edusharing_rediscluster.labels.instance" . | nindent 6 }}
  serviceName: {{ include "edusharing_rediscluster.name" . }}-headless
  template:
    metadata:
      name: {{ include "edusharing_rediscluster.name" . }}
      labels: {{ include "edusharing_rediscluster.labels" . | nindent 8 }}
      annotations:
        checksum/configmap-env: {{ include (print .Template.BasePath "/configmap-env.yaml") . | sha256sum | trunc 63 }}
        checksum/configmap-file: {{ include (print .Template.BasePath "/configmap-file.yaml") . | sha256sum | trunc 63 }}
        {{- if .Values.global.cluster.istio.enabled }}
        sidecar.istio.io/inject: "true"
        {{- end }}
    spec:
      initContainers:
      - name: {{ include "edusharing_rediscluster.name" . }}-init-permission
        image: {{ .Values.global.image.registry }}/{{ .Values.global.image.repository }}-minideb:{{ .Values.global.image.tag }}
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        command:
        - "/bin/bash"
        - "-ec"
        - |
          chown -R {{ .Values.podSecurityContext.runAsUser }}:{{ .Values.podSecurityContext.fsGroup }} /bitnami/redis
        volumeMounts:
        - name: data
          mountPath: /bitnami/redis
          subPath: data/
        securityContext:
          runAsUser: 0
      containers:
      - name: {{ include "edusharing_rediscluster.name" . }}
        image: {{ .Values.global.image.registry }}/{{ .Values.global.image.repository }}-rediscluster:{{ .Values.global.image.tag }}
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        command:
          - "/bin/bash"
          - "-ec"
          - |
            [[ -f /opt/bitnami/redis/etc/redis.conf ]] || {
              cp /opt/bitnami/redis/etc/redis-default.conf /opt/bitnami/redis/etc/redis.conf
            }
            /opt/bitnami/scripts/redis-cluster/entrypoint.sh /opt/bitnami/scripts/redis-cluster/run.sh
        envFrom:
        - configMapRef:
            name: {{ include "edusharing_rediscluster.name" . }}-env
        ports:
        - name: api
          containerPort: 6379
        - name: gossip
          containerPort: 16379
        volumeMounts:
        - name: data
          mountPath: /bitnami/redis
          subPath: data/
        - name: file
          mountPath: /opt/bitnami/redis/etc/redis-default.conf
          subPath: redis-default.conf
        {{- with .Values.livenessProbe }}
        livenessProbe:
          tcpSocket:
            port: api
          failureThreshold: {{ .failureThreshold }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          timeoutSeconds: {{ .timeoutSeconds }}
        {{- end }}
        {{- with .Values.readinessProbe }}
        readinessProbe:
          exec:
            command:
            - "/bin/bash"
            - "-ec"
            - |
              [[ $(redis-cli ping) == "PONG" ]] || exit 1
          failureThreshold: {{ .failureThreshold }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          successThreshold: {{ .successThreshold }}
          timeoutSeconds: {{ .timeoutSeconds }}
        {{- end }}
        {{- with .Values.resources }}
        resources: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.securityContext }}
        securityContext: {{ toYaml . | nindent 10 }}
        {{- end }}
      {{- with .Values.global.image.pullSecrets }}
      imagePullSecrets: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{ with .Values.terminationGracePeriod }}
      terminationGracePeriodSeconds: {{ . }}
      {{- end }}
      {{- if or .Values.nodeAffinity .Values.podAntiAffinity }}
      affinity:
        {{- with .Values.nodeAffinity }}
        nodeAffinity: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- if .Values.podAntiAffinity }}
        podAntiAffinity:
          {{- if eq .Values.podAntiAffinity "hard" }}
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels: {{ include "edusharing_rediscluster.labels.instance" . | nindent 16 }}
          {{- else if eq .Values.podAntiAffinity "soft" }}
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels: {{ include "edusharing_rediscluster.labels.instance" . | nindent 18 }}
          {{- end }}
        {{- end }}
      {{- end }}
      volumes:
      - name: file
        configMap:
          name: {{ include "edusharing_rediscluster.name" . }}-file
  volumeClaimTemplates:
  - metadata:
      name: data
      labels: {{ include "edusharing_rediscluster.labels" . | nindent 8 }}
    spec: {{ merge .Values.persistence.data.spec .Values.global.cluster.storage.data.spec | toYaml | nindent 6 }}
