version: '3.7'

services:

  repository-database:
    ports:
      - "${COMMON_BIND_HOST:-127.0.0.1}:${REPOSITORY_DATABASE_PORT:-8000}:5432"

  repository-mailcatcher:
    ports:
      - "${COMMON_BIND_HOST:-127.0.0.1}:${REPOSITORY_MAILCATCHER_PORT_SMTP:-8025}:1025"
      - "${COMMON_BIND_HOST:-127.0.0.1}:${REPOSITORY_MAILCATCHER_PORT_HTTP:-8026}:1080"

  repository-search-solr6:
    command: ["solr6/solr/bin/solr", "start", "-f","-p","8080", "-Dcreate.alfresco.defaults=alfresco,archive"]
    environment:
      JPDA_ADDRESS: "0.0.0.0:5005"
    ports:
      - "${COMMON_BIND_HOST:-127.0.0.1}:${REPOSITORY_SEARCH_SOLR6_PORT_HTTP:-8200}:8080"
      - "${COMMON_BIND_HOST:-127.0.0.1}:${REPOSITORY_SEARCH_SOLR6_PORT_JPDA:-8201}:5005"

  repository-service:
    command: ["catalina.sh", "jpda", "run"]
    environment:
      JPDA_ADDRESS: "0.0.0.0:5005"
    ports:
      - "${COMMON_BIND_HOST:-127.0.0.1}:${REPOSITORY_SERVICE_PORT_JPDA:-8101}:5005"

  repository-transform-edu-sharing:
    environment:
      JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8000"
    ports:
      - "${COMMON_BIND_HOST:-127.0.0.1}:${REPOSITORY_EDU_SHARING_TRANSFORM_PORT_JPDA:-8601}:8000"
