version: '3.7'

services:

  repository-database:
    image: "${docker.registry}/${docker.repository}/${docker.prefix}-deploy-docker-build-postgresql:${docker.tag}"

  repository-mailcatcher:
    image: "${docker.registry}/${docker.repository}/${docker.prefix}-deploy-docker-build-mailcatcher:${docker.tag}"

  repository-search-solr:
    image: "${docker.registry}/${docker.repository}/${docker.prefix}-deploy-docker-repository-build-search-solr:${docker.tag}"

  repository-service:
    image: "${docker.registry}/${docker.repository}/${docker.prefix}-deploy-docker-repository-build-service:${docker.tag}"

  repository-transform:
    image: "${docker.registry}/${docker.repository}/${docker.prefix}-deploy-docker-repository-build-transform:${docker.tag}"

  repository-alfresco-transform-core-aio:
    image: "${docker.registry}/${docker.repository}/${docker.prefix}-deploy-docker-repository-build-alfresco-transform-core-aio:${docker.tag}"

  repository-transform-edu-sharing:
    image: "${docker.registry}/${docker.repository}/${docker.prefix}-deploy-docker-repository-build-transform-edu-sharing:${docker.tag}"

  repository-activemq:
    image: "${docker.registry}/${docker.repository}/${docker.prefix}-deploy-docker-build-activemq:${docker.tag}"