version: '3.7'

services:

  repository-database:
    image: "${docker.registry}/${docker.repository}/${docker.prefix}-deploy-docker-build-postgresql:${docker.tag}"

  repository-search-solr6:
    image: "${docker.registry}/${docker.repository}/${docker.prefix}-deploy-docker-repository-build-search-solr6:${docker.tag}"

  repository-service:
    image: "${docker.registry}/${docker.repository}/${docker.prefix}-deploy-docker-repository-build-service:${docker.tag}"

  repository-transform:
    image: "${docker.registry}/${docker.repository}/${docker.prefix}-deploy-docker-repository-build-transform:${docker.tag}"
