########################################################################################################################
# GLOBAL
########################################################################################################################

global:

  cluster:

    istio:
      enabled: false

    storage:
      data:
        spec: {}
#          storageClassName:

  image:
    registry: ${docker.registry}
    repository: ${docker.image}
    tag: ${docker.tag}
    pullPolicy: Always
    pullSecrets: []

########################################################################################################################
# LOCAL
########################################################################################################################

nameOverride: edusharing-postgresql

########################################################################################################################

service:

  port:
    api: 5432

########################################################################################################################

config:

  database: postgresql
  username: postgresql
  password: postgresql

  extra:
    max_connections: "300"

########################################################################################################################

nodeAffinity: {}

tolerations: []

########################################################################################################################

persistence:

  data:
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi

########################################################################################################################

podSecurityContext:

  runAsUser: 1001
  fsGroup: 1001

securityContext:

  capabilities:
    drop:
    - ALL

########################################################################################################################

terminationGracePeriod: 120

livenessProbe:

  failureThreshold: 3
  initialDelaySeconds: 1200
  periodSeconds: 10
  timeoutSeconds: 5

readinessProbe:

  failureThreshold: 1
  initialDelaySeconds: 30
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5

########################################################################################################################

resources:

  limits:
    cpu: 200m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 1Gi

########################################################################################################################

metrics:

  enabled: true

  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 100m
      memory: 100Mi

  securityContext: {}

########################################################################################################################
