apiVersion: v2

name: ${helm.prefix}
description: ${helm.prefix}

icon: ${helm.chart.icon}

version: ${helm.chart.version}
appVersion: ${docker.tag}
kubeVersion: "${helm.kube.version}"

dependencies:

  - name: ${helm.prefix}-rediscluster
    version: ${helm.chart.version}
    alias: edusharing_rediscluster
    condition: edusharing_rediscluster.enabled

  - name: ${helm.prefix}-repository
    version: ${helm.chart.version}
    alias: edusharing_repository
    condition: edusharing_repository.enabled

  - name: ${helm.prefix}-services-rendering
    version: ${helm.chart.version}
    alias: edusharing_services_rendering
    condition: edusharing_services_rendering.enabled

  - name: ${helm.prefix}-postgresql
    version: ${helm.chart.version}
    alias: edusharing_repository_postgresql
    condition: edusharing_repository_postgresql.enabled

  - name: ${helm.prefix}-rediscluster
    version: ${helm.chart.version}
    alias: edusharing_repository_rediscluster
    condition: edusharing_repository_rediscluster.enabled

  - name: ${helm.prefix}-repository-search-solr
    version: ${helm.chart.version}
    alias: edusharing_repository_search_solr
    condition: edusharing_repository_search_solr.enabled

  - name: ${helm.prefix}-repository-service
    version: ${helm.chart.version}
    alias: edusharing_repository_service
    condition: edusharing_repository_service.enabled

  ${helm.edusharing_repository_antivirus.line1}
  ${helm.edusharing_repository_antivirus.line2}
  ${helm.edusharing_repository_antivirus.line3}
  ${helm.edusharing_repository_antivirus.line4}
  
  ${helm.edusharing_repository_mongo.line1}
  ${helm.edusharing_repository_mongo.line2}
  ${helm.edusharing_repository_mongo.line3}
  ${helm.edusharing_repository_mongo.line4}

  ${helm.edusharing_repository_search_elastic_index.line1}
  ${helm.edusharing_repository_search_elastic_index.line2}
  ${helm.edusharing_repository_search_elastic_index.line3}
  ${helm.edusharing_repository_search_elastic_index.line4}
  
  ${helm.edusharing_repository_search_elastic_tracker.line1}
  ${helm.edusharing_repository_search_elastic_tracker.line2}
  ${helm.edusharing_repository_search_elastic_tracker.line3}
  ${helm.edusharing_repository_search_elastic_tracker.line4}

  ${helm.edusharing_repository_transform.line1}
  ${helm.edusharing_repository_transform.line2}
  ${helm.edusharing_repository_transform.line3}
  ${helm.edusharing_repository_transform.line4}
