apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "edusharing_repository_search_elastic_tracker.name" . }}
  labels: {{ include "edusharing_repository_search_elastic_tracker.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels: {{ include "edusharing_repository_search_elastic_tracker.labels.instance" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "edusharing_repository_search_elastic_tracker.labels" . | nindent 8 }}
      annotations:
        checksum/configmap-env: {{ include (print .Template.BasePath "/configmap-env.yaml") . | sha256sum | trunc 63 }}
        checksum/secret-env: {{ include (print .Template.BasePath "/secret-env.yaml") . | sha256sum | trunc 63 }}
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8081"
        prometheus.io/scrape: {{ .Values.metrics.enabled | quote }}
        sidecar.istio.io/inject: {{ .Values.global.cluster.istio.enabled | quote }}
    spec:
      containers:
      - name: {{ include "edusharing_repository_search_elastic_tracker.name" . }}
        image: {{ .Values.global.image.registry }}/{{ .Values.global.image.repository }}-repository-search-elastic-tracker:{{ .Values.global.image.tag }}
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        envFrom:
        - configMapRef:
            name: {{ include "edusharing_repository_search_elastic_tracker.name" . }}-env
        - secretRef:
            name: {{ include "edusharing_repository_search_elastic_tracker.name" . }}-env
        ports:
        - name: mgmt
          containerPort: 8081
        - name: jmx
          containerPort: 7199
        {{- with .Values.livenessProbe }}
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: mgmt
          failureThreshold: {{ .failureThreshold }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          timeoutSeconds: {{ .timeoutSeconds }}
        {{- end }}
        {{- with .Values.readinessProbe }}
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: mgmt
          failureThreshold: {{ .failureThreshold }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          successThreshold: {{ .successThreshold }}
          timeoutSeconds: {{ .timeoutSeconds }}
        {{- end }}
        {{- with .Values.resources }}
        resources: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.securityContext }}
        securityContext: {{ toYaml . | nindent 10 }}
        {{- end }}
      {{- with .Values.global.image.pullSecrets }}
      imagePullSecrets: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{ with .Values.terminationGracePeriod }}
      terminationGracePeriodSeconds: {{ . }}
      {{- end }}
      {{- with .Values.nodeAffinity }}
      affinity:
        nodeAffinity: {{ toYaml . | nindent 10 }}
      {{- end }}
