apiVersion: v1
kind: Secret
metadata:
  name: {{ include "edusharing_repository_search_elastic_tracker.name" . }}-env
  labels: {{ include "edusharing_repository_search_elastic_tracker.labels" . | nindent 4 }}
type: Opaque
data:
  REPOSITORY_SERVICE_ADMIN_PASS: {{ .Values.config.repository.password | b64enc | quote }}