########################################################################################################################
# GLOBAL
########################################################################################################################

global:

  image:
    registry: ${docker.registry}
    pullPolicy: Always
    pullSecrets: []

  istio:
    enabled: false

########################################################################################################################
# LOCAL
########################################################################################################################

nameOverride: edusharing-repository-transform
fullnameOverride: ""

########################################################################################################################

image:

  repository: ${docker.image}-repository-transform
  tag: ${docker.tag}

########################################################################################################################

replicaCount: 1

########################################################################################################################

service:

  port:
    api: 8100

########################################################################################################################

nodeAffinity: {}
podAntiAffinity: "" # "soft" or "hard"

tolerations: []

########################################################################################################################

podSecurityContext:

  runAsUser: 1000

securityContext:

  capabilities:
    drop:
      - ALL

########################################################################################################################

terminationGracePeriod: 120

livenessProbe:

  failureThreshold: 3
  initialDelaySeconds: 300
  periodSeconds: 10
  timeoutSeconds: 5

readinessProbe:

  failureThreshold: 1
  initialDelaySeconds: 30
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5

########################################################################################################################

resources:

  limits:
    cpu: 100m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 1Gi

########################################################################################################################
