########################################################################################################################
# GLOBAL
########################################################################################################################

global:

  cluster:

    istio:
      enabled: false

    storage:
      data:
        spec: {}
#          storageClassName:

  image:
    registry: ${docker.registry}
    repository: ${docker.image}
    tag: ${docker.tag}
    pullPolicy: Always
    pullSecrets: []

########################################################################################################################
# LOCAL
########################################################################################################################

nameOverride: edusharing-repository-search-solr4

########################################################################################################################

replicaCount: 1

########################################################################################################################

service:

  port:
    api: 8080

########################################################################################################################

config:

  jvm:
    ram:
      minPercentage: "75.0"
      maxPercentage: "75.0"

  repository:
    host: edusharing-repository-service
    port: 8080

########################################################################################################################

nodeAffinity: {}
podAntiAffinity: "" # "soft" or "hard"

tolerations: []

########################################################################################################################

persistence:

  data:
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi

########################################################################################################################

podSecurityContext:

  runAsUser: 1000
  fsGroup: 1000

securityContext:

  capabilities:
    drop:
    - ALL

########################################################################################################################

terminationGracePeriod: 120

livenessProbe:

  failureThreshold: 3
  initialDelaySeconds: 900
  periodSeconds: 10
  timeoutSeconds: 5

readinessProbe:

  failureThreshold: 1
  initialDelaySeconds: 30
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5

########################################################################################################################

resources:

  limits:
    cpu: 500m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 2Gi

########################################################################################################################

metrics:

  enabled: true

########################################################################################################################
