version: '3.7'

services:

  cache:
    image: "${docker.repository}/${docker.prefix}-deploy-docker-build-redis:${docker.tag}"
    container_name: "cache_${COMPOSE_PROJECT_NAME}"
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    expose:
      - 6379

  profiler:
    image: "${docker.repository}/${docker.prefix}-deploy-docker-build-profiler:${docker.tag}"
    container_name: "profiler_${COMPOSE_PROJECT_NAME}"
    pid: "host"
    userns_mode: "host"
    privileged: true
    volumes:
      - "profiler:/opt/profiler"

volumes:
  profiler:
