apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "edusharing_repository_service.fullname" . }}-redis
  labels: {{ include "edusharing_repository_service.labels" . | nindent 4 }}
data:
  redisson.yaml: |
    {{- if .Values.edusharing_rediscluster.enabled }}
    clusterServersConfig:
      nodeAddresses:
        - redis://{{ include "edusharing_repository_service.edusharing_rediscluster" . }}:{{ .Values.edusharing_rediscluster.service.port.api }}
      readMode: "MASTER"
      subscriptionMode: "MASTER"
    {{- end }}
    {{- .Values.config.cache.extra | indent 4 }}
