{{- if and .Values.global.istio.enabled (.Capabilities.APIVersions.Has "networking.istio.io/v1beta1") }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ include "edusharing_repository_service.fullname" . }}
  namespace: {{ .Values.global.istio.namespace }}
  labels: {{ include "edusharing_repository_service.labels" . | nindent 4 }}
spec:
  selector:
    app: istio-ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts: {{ toYaml .Values.ingress.hosts | nindent 6 }}
  {{- range .Values.ingress.tls }}
  - port:
    number: 443
    name: https
    protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: {{ .secretName }}
    hosts: {{ toYaml .hosts | nindent 8 }}
  {{- end }}
{{- end }}
