version: '3.4'

services:

  rendering-cache:
    image: "redis:${rendering.redis.server.version}"

  rendering-database:
    image: "mariadb:${rendering.mariadb.server.version}"
    command: ["mysqld", "--bind-address=0.0.0.0", "--port=3306", "--max-connections=300" ]
    environment:
      MYSQL_DATABASE: "${RENDERING_DATABASE_NAME:-rendering}"
      MYSQL_PASSWORD: "${RENDERING_DATABASE_PASS:-rendering}"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: "${RENDERING_DATABASE_USER:-rendering}"
      TZ: "Europe/Berlin"
    volumes:
      - "rendering-database-volume:/var/lib/mysql"

  rendering-init:
    image: "${docker.registry}/${project.parent.artifactId}-build-init:${project.version}"
    environment:
      RENDERING_SERVICE_HOST: rendering-service
      RENDERING_SERVICE_PORT: "8080"
      REPOSITORY_SERVICE_HOST: repository-service
      REPOSITORY_SERVICE_PORT: "8080"
      REPOSITORY_SERVICE_ROOT_PASS: "${REPOSITORY_SERVICE_ROOT_PASS:-admin}"
    depends_on:
      - rendering-service

  rendering-service:
    image: "${docker.registry}/${project.parent.artifactId}-build-service:${project.version}"
    environment:
      MY_HOST_EXTERN: "${RENDERING_SERVICE_HOST:-rendering.127.0.0.1.xip.io}"
      MY_HOST_INTERN: rendering-service
      MY_PORT_EXTERN: "${RENDERING_SERVICE_PORT_HTTP:-9100}"
      MY_PORT_INTERN: "8080"
      RENDERING_CACHE_HOST: rendering-cache
      RENDERING_CACHE_PORT: "6379"
      RENDERING_DATABASE_HOST: rendering-database
      RENDERING_DATABASE_NAME: "${RENDERING_DATABASE_NAME:-rendering}"
      RENDERING_DATABASE_PASS: "${RENDERING_DATABASE_PASS:-rendering}"
      RENDERING_DATABASE_PORT: "3306"
      RENDERING_DATABASE_USER: "${RENDERING_DATABASE_USER:-rendering}"
      REPOSITORY_SERVICE_HOST: repository-service
      REPOSITORY_SERVICE_PORT: "8080"
    expose:
      - "8080"
    ports:
      - "${COMMON_BIND_HOST:-127.0.0.1}:${RENDERING_SERVICE_PORT_HTTP:-9100}:8081"
    volumes:
      - "rendering-service-volume:/var/cache/esrender"
    depends_on:
      - rendering-cache
      - rendering-database

volumes:
  rendering-database-volume:
    name: "${COMPOSE_PROJECT_NAME:-deploy}_rendering-database-volume"
    external: true
  rendering-service-volume:
    name: "${COMPOSE_PROJECT_NAME:-deploy}_rendering-service-volume"
    external: true
