apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "edusharing_repository_search_solr.name" . }}-file
  labels: {{ include "edusharing_repository_search_solr.labels.app" . | nindent 4 }}
data:
{{- with .Values.config.override.logging.application }}
  logging-application: | {{ . | nindent 4 }}
{{- end }}
{{- with .Values.config.override.logging.server }}
  logging-server: | {{ . | nindent 4 }}
{{- end }}
