apiVersion: v2

name: ${helm.prefix}_services_rendering
description: ${helm.prefix}_services_rendering

icon: ${helm.chart.icon}

version: ${helm.chart.version}
appVersion: ${docker.tag}
kubeVersion: "${helm.kube.version}"
