apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "edusharing_repository_service.name" . }}-env
  labels: {{ include "edusharing_repository_service.labels" . | nindent 4 }}
data:
  CATALINA_OPTS: >-
    -XX:MinRAMPercentage={{ .Values.config.jvm.ram.minPercentage }}
    -XX:MaxRAMPercentage={{ .Values.config.jvm.ram.maxPercentage }}
    -Dcaches.join=kubernetes
    -Dcaches.join.kubernetes.dns={{ printf "%s-headless.%s.svc.%s" (include "edusharing_repository_service.name" .) .Release.Namespace .Values.global.cluster.domain }}
    -Dcaches.backupCount={{ .Values.config.cluster.backupCount }}
    -Dcaches.readBackupData={{ .Values.config.cluster.readBackupData }}
    -Dhazelcast.graceful.shutdown.max.wait={{ .Values.terminationGracePeriod }}
    -Dcom.sun.management.jmxremote
    -Dcom.sun.management.jmxremote.authenticate=false
    -Dcom.sun.management.jmxremote.port=7199
    -Dcom.sun.management.jmxremote.ssl=false
    {{- if .Values.metrics.enabled }}
    -javaagent:/opt/alfresco/tomcat/agent/jmx_prometheus_javaagent.jar=9090:/opt/alfresco/tomcat/agent/jmx-exporter-config.yaml
    {{- end }}
  REPOSITORY_CACHE_HOST: {{ .Values.config.cache.host | quote }}
  REPOSITORY_CACHE_PORT: {{ .Values.config.cache.port | quote }}
  REPOSITORY_DATABASE_DRIV: {{ .Values.config.database.driver | quote }}
  REPOSITORY_DATABASE_HOST: {{ .Values.config.database.host | quote }}
  REPOSITORY_DATABASE_NAME: {{ .Values.config.database.database | quote }}
  REPOSITORY_DATABASE_OPTS: {{ .Values.config.database.options | quote }}
  REPOSITORY_DATABASE_POOL_MAX: {{ .Values.config.database.pool.max | quote }}
  REPOSITORY_DATABASE_POOL_SQL: {{ .Values.config.database.pool.sql | quote }}
  REPOSITORY_DATABASE_PORT: {{ .Values.config.database.port | quote }}
  REPOSITORY_DATABASE_PROT: {{ .Values.config.database.protocol | quote }}
  REPOSITORY_SEARCH_ELASTIC_HOST: {{ .Values.config.search.elastic.host | quote }}
  REPOSITORY_SEARCH_ELASTIC_PORT: {{ .Values.config.search.elastic.port | quote }}
  REPOSITORY_SEARCH_SOLR4_HOST: {{ .Values.config.search.solr4.host | quote }}
  REPOSITORY_SEARCH_SOLR4_PORT: {{ .Values.config.search.solr4.port | quote }}
  REPOSITORY_SERVICE_BIND: {{ if .Values.global.cluster.istio.enabled }}"127.0.0.1"{{ else }}"0.0.0.0"{{ end }}
  REPOSITORY_SERVICE_HOME_APPID: {{ .Values.config.home.appid | quote }}
  REPOSITORY_SERVICE_HOME_AUTH: {{ if .Values.config.saml.enabled }}"shibboleth"{{ else }}""{{ end }}
  REPOSITORY_SERVICE_HOME_PROVIDER: {{ if .Values.config.search.elastic.enabled }}"org.edu_sharing.service.provider.ElasticSearchProvider"{{ else }}""{{ end }}
  REPOSITORY_SERVICE_HOST_EXTERNAL: {{ .Values.ingress.hosts | first | quote }}
  REPOSITORY_SERVICE_HOST_INTERNAL: {{ include "edusharing_repository_service.name" . | quote }}
  REPOSITORY_SERVICE_PATH_EXTERNAL: {{ .Values.ingress.paths | first | quote }}
  REPOSITORY_SERVICE_PORT_EXTERNAL: {{ if .Values.ingress.tls }}"443"{{ else }}"80"{{ end }}
  REPOSITORY_SERVICE_PORT_INTERNAL: {{ .Values.service.port.api.internal | quote }}
  REPOSITORY_SERVICE_PROT_EXTERNAL: {{ if .Values.ingress.tls }}"https"{{ else }}"http"{{ end }}
  REPOSITORY_SMTP_AUTH: {{ .Values.config.smtp.auth | quote }}
  REPOSITORY_SMTP_FROM: {{ .Values.config.smtp.from | quote }}
  REPOSITORY_SMTP_HOST: {{ .Values.config.smtp.host | quote }}
  REPOSITORY_SMTP_PASS: {{ .Values.config.smtp.password | quote }}
  REPOSITORY_SMTP_PORT: {{ .Values.config.smtp.port | quote }}
  REPOSITORY_SMTP_REPL: {{ .Values.config.smtp.addReplyTo | quote }}
  REPOSITORY_SMTP_USER: {{ .Values.config.smtp.username | quote }}
  REPOSITORY_TRANSFORM_BIND: "127.0.0.1"
  REPOSITORY_TRANSFORM_HOST: "127.0.0.1"
  REPOSITORY_TRANSFORM_PORT: "8100"
