apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "edusharing_elasticsearch.fullname" . }}
  labels: {{ include "edusharing_elasticsearch.labels" . | nindent 4 }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels: {{ include "edusharing_elasticsearch.labels.instance" . | nindent 6 }}
