services:

  repository-cache:
    ports:
      - "127.0.0.1:${REPOSITORY_CACHE_PORT_REDIS:-8001}:6379"

  repository-database:
    ports:
      - "127.0.0.1:${REPOSITORY_DATABASE_PORT_SQL:-8000}:5432"

  repository-search-elastic:
    ports:
      - "127.0.0.1:${REPOSITORY_SEARCH_ELASTIC_PORT_HTTP:-8300}:9200"

  repository-search-elastic-tracker:
    environment:
      JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8000"
    ports:
      - "127.0.0.1:${REPOSITORY_SEARCH_ELASTIC_TRACKER_PORT_JPDA:-8401}:8000"

  repository-search-solr4:
    command: ["catalina.sh", "jpda", "run"]
    environment:
      JPDA_ADDRESS: "0.0.0.0:5005"
    ports:
      - "127.0.0.1:${REPOSITORY_SEARCH_SOLR4_PORT_HTTP:-8200}:8080"
      - "127.0.0.1:${REPOSITORY_SEARCH_SOLR4_PORT_JPDA:-8201}:5005"

  repository-service:
    command: ["catalina.sh", "jpda", "run"]
    environment:
      JPDA_ADDRESS: "0.0.0.0:5005"
    ports:
      - "127.0.0.1:${REPOSITORY_SERVICE_PORT_JPDA:-8101}:5005"
