apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "edusharing_rendering_service.fullname" . }}-env
  labels: {{ include "edusharing_rendering_service.labels" . | nindent 4 }}
data:
  RENDERING_CACHE_HOST: {{ if .Values.edusharing_rediscluster.enabled }}{{ include "edusharing_rendering_service.edusharing_rediscluster" . | quote }}{{ else }}{{ .Values.config.cache.host | quote }}{{ end }}
  RENDERING_CACHE_OPTS: {{ .Values.config.cache.extra | quote }}
  RENDERING_CACHE_PORT: {{ if .Values.edusharing_rediscluster.enabled }}{{ .Values.edusharing_rediscluster.service.port.api | quote }}{{ else }}{{ .Values.config.cache.port | quote }}{{ end }}
  RENDERING_CACHE_PROT: {{ if .Values.edusharing_rediscluster.enabled }}"seed[]="{{ else }}{{ .Values.config.cache.protocol | quote }}{{ end }}
  RENDERING_CACHE_TYPE: {{ if .Values.edusharing_rediscluster.enabled }}"rediscluster"{{ else }}{{ .Values.config.cache.type | quote }}{{ end }}
  RENDERING_DATABASE_DRIV: {{ if .Values.edusharing_rendering_mariadb.enabled }}"mysql"{{ else }}{{ .Values.config.database.driver | quote }}{{ end }}
  RENDERING_DATABASE_HOST: {{ if .Values.edusharing_rendering_mariadb.enabled }}{{ include "edusharing_rendering_service.edusharing_rendering_mariadb" . | quote }}{{ else }}{{ .Values.config.database.host | quote }}{{ end }}
  RENDERING_DATABASE_NAME: {{ .Values.config.database.database | quote }}
  RENDERING_DATABASE_PORT: {{ if .Values.edusharing_rendering_mariadb.enabled }}{{ .Values.edusharing_rendering_mariadb.service.port.api | quote }}{{ else }}{{ .Values.config.database.port | quote }}{{ end }}
  RENDERING_SERVICE_BIND: {{ if .Values.global.istio.enabled }}"127.0.0.1"{{ else }}"0.0.0.0"{{ end }}
  RENDERING_SERVICE_HOST_EXTERNAL: {{ .Values.ingress.hosts | first | quote }}
  RENDERING_SERVICE_HOST_INTERNAL: {{ include "edusharing_rendering_service.fullname" . | quote }}
  RENDERING_SERVICE_PATH_EXTERNAL: {{ .Values.ingress.paths | first | quote }}
  RENDERING_SERVICE_PORT_EXTERNAL: {{ if .Values.ingress.tls }}"443"{{ else }}"80"{{ end }}
  RENDERING_SERVICE_PORT_INTERNAL: {{ .Values.service.port.api.internal | quote }}
  RENDERING_SERVICE_PROT_EXTERNAL: {{ if .Values.ingress.tls }}"https"{{ else }}"http"{{ end }}
  REPOSITORY_SERVICE_HOST: {{ include "edusharing_rendering_service.edusharing_repository_service" . | quote }}
  REPOSITORY_SERVICE_PORT: {{ .Values.edusharing_repository_service.service.port.api.internal | quote }}
