apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "edusharing_rendering_service.fullname" . }}-init
  labels: {{ include "edusharing_rendering_service.labels" . | nindent 4 }}
    app.kubernetes.io/component: init
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-delete-policy: hook-succeeded
    {{- if .Values.global.istio.enabled }}
    sidecar.istio.io/inject: "true"
    {{- end }}
spec:
  completions: 1
  parallelism: 1
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: {{ include "edusharing_rendering_service.name" . }}
        image: {{ .Values.global.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        args: ["init.sh"]
        envFrom:
        - configMapRef:
            name: {{ include "edusharing_rendering_service.fullname" . }}-env
        - secretRef:
            name: {{ include "edusharing_rendering_service.fullname" . }}-env
        {{- with .Values.resources }}
        resources: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.securityContext }}
        securityContext: {{ toYaml . | nindent 10 }}
        {{- end }}
      {{- with .Values.global.image.pullSecrets }}
      imagePullSecrets: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.terminationGracePeriod }}
      terminationGracePeriodSeconds: {{ . }}
      {{- end }}
      {{- with .Values.nodeAffinity }}
      affinity:
        nodeAffinity: {{ toYaml . | nindent 10 }}
      {{- end }}
