{{- if .Values.persistence.share.create }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "edusharing_rendering_service.pvc.share" . }}
  labels: {{ include "edusharing_rendering_service.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
spec: {{ merge .Values.persistence.share.spec .Values.global.cluster.storage.share.spec | toYaml | nindent 2 }}
{{- end }}
