apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "edusharing_rendering_service.fullname" . }}
  labels: {{ include "edusharing_rendering_service.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels: {{ include "edusharing_rendering_service.labels.instance" . | nindent 6 }}
