########################################################################################################################
# GLOBAL
########################################################################################################################

global:

  cluster:

    cert:
      annotations: {}
#        cert-manager.io/cluster-issuer:
#        cert-manager.io/issuer:

    istio:
      enabled: false
      gateway:
        selector:
          app: istio-ingressgateway

    storage:
      share:
        spec: {}
#          storageClassName:

  image:
    registry: ${docker.registry}
    repository: ${docker.image}
    tag: ${docker.tag}
    pullPolicy: Always
    pullSecrets: []

########################################################################################################################
# LOCAL
########################################################################################################################

nameOverride: edusharing-rendering-service

########################################################################################################################

replicaCount: 1

########################################################################################################################

service:

  port:
    api:
      internal: 8080
      external: 8081

########################################################################################################################

ingress:

  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/session-cookie-name: edusharing-rendering
    nginx.ingress.kubernetes.io/session-cookie-path: "*"
    nginx.ingress.kubernetes.io/proxy-body-size: 5g
#    nginx.ingress.kubernetes.io/configuration-snippet: |
#      location /esrender/application/ {return 403;}
#      location /esrender/conf/ {return 403;}

  hosts:
  - rendering.127.0.0.1.xip.io

  tls: []
#  - secretName: edusharing-rendering-tls
#    hosts:
#    - rendering.127.0.0.1.xip.io

  paths:
  - /esrender

########################################################################################################################

config:

  cache:
    host: edusharing-rendering-rediscluster
    port: 6379
    # https://github.com/phpredis/phpredis/blob/develop/cluster.markdown#session-handler
    type: rediscluster
    protocol: "seed[]="
    options: "&distribute=0&failover=error&prefix=edusharing-rendering:"

  cachecleaner:
    schedule: "*/10 * * * *"

  database:
    driver: mysql
    host: edusharing-rendering-mariadb
    port: 3306
    database: rendering
    username: rendering
    password: rendering

  repository:
    host: edusharing-repository-service
    port: 8080
    password: admin

########################################################################################################################

persistence:

  share:
    create: true
    spec:
      accessModes: [ "ReadWriteMany" ]
      resources:
        requests:
          storage: 5Gi

########################################################################################################################

nodeAffinity: {}
podAntiAffinity: ""

tolerations: []

########################################################################################################################

podSecurityContext:

  runAsUser: 0
  fsGroup: 33

securityContext: {}

########################################################################################################################

terminationGracePeriod: 120

livenessProbe:

  failureThreshold: 3
  initialDelaySeconds: 300
  periodSeconds: 10
  timeoutSeconds: 5

readinessProbe:

  failureThreshold: 1
  initialDelaySeconds: 30
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5

########################################################################################################################

resources:

  limits:
    cpu: 500m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 2Gi

########################################################################################################################
