apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "edusharing_repository_service.name" . }}-file
  labels: {{ include "edusharing_repository_service.labels" . | nindent 4 }}
data:
  redisson.yaml: |
    {{- if eq .Values.config.cache.type "rediscluster" }}
    clusterServersConfig:
      nodeAddresses:
        - redis://{{ .Values.config.cache.host }}:{{ .Values.config.cache.port }}
{{ .Values.config.cache.options | indent 6 }}
    {{- else }}
    singleServerConfig:
      address: redis://{{ .Values.config.cache.host }}:{{ .Values.config.cache.port }}
{{ .Values.config.cache.options | indent 6 }}
    {{- end }}
{{ .Values.config.cache.commons | indent 4 }}
