########################################################################################################################
# GLOBAL
########################################################################################################################

global:

  cluster:

    istio:
      enabled: false

  image:
    registry: ${docker.registry}
    repository: ${docker.image}
    tag: ${docker.tag}
    pullPolicy: Always
    pullSecrets: []

########################################################################################################################
# LOCAL
########################################################################################################################

nameOverride: edusharing-repository-search-elastic-tracker

########################################################################################################################

config:

  jvm:
    debug: false
    ram:
      minPercentage: "95.0"
      maxPercentage: "95.0"

  options: ""

  repository:
    host: edusharing-repository-service
    port: 8080
    password: admin

  search:

    elastic:
      host: edusharing-repository-search-elastic
      port: 9200

########################################################################################################################

nodeAffinity: {}

tolerations: []

########################################################################################################################

podSecurityContext:

  runAsUser: 1000
  fsGroup: 1000

securityContext:

  capabilities:
    drop:
    - ALL

########################################################################################################################

terminationGracePeriod: 120

livenessProbe:

  failureThreshold: 3
  initialDelaySeconds: 1200
  periodSeconds: 10
  timeoutSeconds: 5

readinessProbe:

  failureThreshold: 1
  initialDelaySeconds: 30
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5

########################################################################################################################

resources:

  limits:
    cpu: 500m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 2Gi

########################################################################################################################

metrics:

  enabled: true

########################################################################################################################
