apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "edusharing_repository_search_solr4.name" . }}
  labels: {{ include "edusharing_repository_search_solr4.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{ include "edusharing_repository_search_solr4.labels.instance" . | nindent 6 }}
  serviceName: {{ include "edusharing_repository_search_solr4.name" . }}-headless
  template:
    metadata:
      name: {{ include "edusharing_repository_search_solr4.name" . }}
      labels: {{ include "edusharing_repository_search_solr4.labels" . | nindent 8 }}
      annotations:
        checksum/configmap-env: {{ include (print .Template.BasePath "/configmap-env.yaml") . | sha256sum | trunc 63 }}
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9090"
        prometheus.io/scrape: {{ .Values.metrics.enabled | quote }}
        sidecar.istio.io/inject: {{ .Values.global.cluster.istio.enabled | quote }}
    spec:
      initContainers:
      - name: {{ include "edusharing_repository_search_solr4.name" . }}-init-permission
        image: {{ .Values.global.image.registry }}/{{ .Values.global.image.repository }}-minideb:{{ .Values.global.image.tag }}
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        command:
        - "/bin/bash"
        - "-ec"
        - |
          chown -R {{ .Values.podSecurityContext.runAsUser }}:{{ .Values.podSecurityContext.fsGroup }} /usr/local/alfresco/alf_data
        volumeMounts:
        - name: data
          mountPath: /usr/local/alfresco/alf_data
          subPath: data/
        securityContext:
          runAsUser: 0
      containers:
      - name: {{ include "edusharing_repository_search_solr4.name" . }}
        image: {{ .Values.global.image.registry }}/{{ .Values.global.image.repository }}-repository-search-solr4:{{ .Values.global.image.tag }}
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        envFrom:
        - configMapRef:
            name: {{ include "edusharing_repository_search_solr4.name" . }}-env
        ports:
        - name: api
          containerPort: 8080
        - name: jmx
          containerPort: 7199
        {{- if .Values.metrics.enabled }}
        - name: metric
          containerPort: 9090
        {{- end }}
        volumeMounts:
        - name: data
          mountPath: /usr/local/alfresco/alf_data
          subPath: data/
        {{- with .Values.livenessProbe }}
        livenessProbe:
          tcpSocket:
            port: api
          failureThreshold: {{ .failureThreshold }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          timeoutSeconds: {{ .timeoutSeconds }}
        {{- end }}
        {{- with .Values.readinessProbe }}
        readinessProbe:
          httpGet:
            path: /solr4
            port: api
          failureThreshold: {{ .failureThreshold }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          successThreshold: {{ .successThreshold }}
          timeoutSeconds: {{ .timeoutSeconds }}
        {{- end }}
        {{- with .Values.resources }}
        resources: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.securityContext }}
        securityContext: {{ toYaml . | nindent 10 }}
        {{- end }}
      {{- with .Values.global.image.pullSecrets }}
      imagePullSecrets: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{ with .Values.terminationGracePeriod }}
      terminationGracePeriodSeconds: {{ . }}
      {{- end }}
      {{- if or .Values.nodeAffinity .Values.podAntiAffinity }}
      affinity:
        {{- with .Values.nodeAffinity }}
        nodeAffinity: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- if .Values.podAntiAffinity }}
        podAntiAffinity:
          {{- if eq .Values.podAntiAffinity "hard" }}
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels: {{ include "edusharing_repository_search_solr4.labels.instance" . | nindent 16 }}
          {{- else if eq .Values.podAntiAffinity "soft" }}
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels: {{ include "edusharing_repository_search_solr4.labels.instance" . | nindent 18 }}
          {{- end }}
        {{- end }}
      {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: data
      labels: {{ include "edusharing_repository_search_solr4.labels" . | nindent 8 }}
    spec: {{ merge .Values.persistence.data.spec .Values.global.cluster.storage.data.spec | toYaml | nindent 6 }}
